title: Kelvin Li 
logo: /assets/img/logo.png
description: A little spot for me in this vast journey of life.
show_downloads: false
google_analytics: []
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
